"""create all tables

Revision ID: ebfdde5434f0
Revises: 5560d9bdbc7e
Create Date: 2025-10-29 17:55:28.166097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebfdde5434f0'
down_revision: Union[str, Sequence[str], None] = '5560d9bdbc7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('localisation', sa.String(), nullable=False),
    sa.Column('adresse_complet', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('surface', sa.Float(), nullable=False),
    sa.Column('chambres', sa.Integer(), nullable=False),
    sa.Column('salle_de_bain', sa.Integer(), nullable=False),
    sa.Column('equipement', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('images', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_table('properties')
    # ### end Alembic commands ###
